- https://www.kaggle.com/c/avazu-ctr-prediction
- XGBoost （特定の変数のみに絞った）
- データ数　train.csv　40428968/40428968
- 　　　　　test.csv　4577465/4577465

In [108]:
train_kensu = 10000000
test_kensu = 4577465
kensu_str  = '10000000'
submit_csv_name = 'submit_only_certain_variables_XGBoost_labelenco' + kensu_str + '.csv'

## 必要なライブラリを読み込む

In [109]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

import seaborn as sns
%matplotlib inline
from sklearn.preprocessing import LabelEncoder

## データ用が多いので、絞って読み込み

In [110]:
train_fname = 'train.csv'
reader = pd.read_csv(train_fname, chunksize=train_kensu)

In [111]:
df_train = reader.get_chunk(train_kensu)

In [112]:
df_train.head()

id  click      hour    C1  banner_pos   site_id site_domain  \
0  1.000009e+18      0  14102100  1005           0  1fbe01fe    f3845767   
1  1.000017e+19      0  14102100  1005           0  1fbe01fe    f3845767   
2  1.000037e+19      0  14102100  1005           0  1fbe01fe    f3845767   
3  1.000064e+19      0  14102100  1005           0  1fbe01fe    f3845767   
4  1.000068e+19      0  14102100  1005           1  fe8cc448    9166c161   

  site_category    app_id app_domain ...  device_type device_conn_type    C14  \
0      28905ebd  ecad2386   7801e8d9 ...            1                2  15706   
1      28905ebd  ecad2386   7801e8d9 ...            1                0  15704   
2      28905ebd  ecad2386   7801e8d9 ...            1                0  15704   
3      28905ebd  ecad2386   7801e8d9 ...            1                0  15706   
4      0569f928  ecad2386   7801e8d9 ...            1                0  18993   

   C15  C16   C17  C18  C19     C20  C21  
0  320   50  1722    0   35      -1   79  
1  320   50  1722    0   35  100084   79  
2  320   50  1722    0   35  100084   79  
3  320   50  1722    0   35  100084   79  
4  320   50  2161    0   35      -1  157  

[5 rows x 24 columns]

In [113]:
df_train.columns

Index(['id', 'click', 'hour', 'C1', 'banner_pos', 'site_id', 'site_domain',
       'site_category', 'app_id', 'app_domain', 'app_category', 'device_id',
       'device_ip', 'device_model', 'device_type', 'device_conn_type', 'C14',
       'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21'],
      dtype='object')

In [114]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000000 entries, 0 to 9999999
Data columns (total 24 columns):
id                  float64
click               int64
hour                int64
C1                  int64
banner_pos          int64
site_id             object
site_domain         object
site_category       object
app_id              object
app_domain          object
app_category        object
device_id           object
device_ip           object
device_model        object
device_type         int64
device_conn_type    int64
C14                 int64
C15                 int64
C16                 int64
C17                 int64
C18                 int64
C19                 int64
C20                 int64
C21                 int64
dtypes: float64(1), int64(14), object(9)
memory usage: 1.8+ GB


## ラベルエンコーディングの実施

In [115]:
def labelencording(df_train):

#LabelEncoderのインスタンスを生成
    le = LabelEncoder()
    #ラベルを覚えさせる
    le = le.fit(df_train['C1'])
    df_train['C1'] = le.transform(df_train['C1'])

    le = le.fit(df_train['banner_pos'])
    df_train['banner_pos'] = le.transform(df_train['banner_pos'])

    le = le.fit(df_train['banner_pos'])
    df_train['banner_pos'] = le.transform(df_train['banner_pos'])

    le = le.fit(df_train['site_id'])
    df_train['site_id'] = le.transform(df_train['site_id'])

    le = le.fit(df_train['site_domain'])
    df_train['site_domain'] = le.transform(df_train['site_domain'])

    le = le.fit(df_train['site_category'])
    df_train['site_category'] = le.transform(df_train['site_category'])

    le = le.fit(df_train['app_id'])
    df_train['app_id'] = le.transform(df_train['app_id'])

    le = le.fit(df_train['app_domain'])
    df_train['app_domain'] = le.transform(df_train['app_domain'])

    le = le.fit(df_train['app_category'])
    df_train['app_category'] = le.transform(df_train['app_category'])

    le = le.fit(df_train['device_id'])
    df_train['device_id'] = le.transform(df_train['device_id'])

    le = le.fit(df_train['device_ip'])
    df_train['device_ip'] = le.transform(df_train['device_ip'])

    le = le.fit(df_train['device_model'])
    df_train['device_model'] = le.transform(df_train['device_model'])

    le = le.fit(df_train['device_type'])
    df_train['device_type'] = le.transform(df_train['device_type'])

    le = le.fit(df_train['device_conn_type'])
    df_train['device_conn_type'] = le.transform(df_train['device_conn_type'])

    le = le.fit(df_train['C14'])
    df_train['C14'] = le.transform(df_train['C14'])

    le = le.fit(df_train['C15'])
    df_train['C15'] = le.transform(df_train['C15'])

    le = le.fit(df_train['C16'])
    df_train['C16'] = le.transform(df_train['C16'])

    le = le.fit(df_train['C17'])
    df_train['C17'] = le.transform(df_train['C17'])

    le = le.fit(df_train['C18'])
    df_train['C18'] = le.transform(df_train['C18'])

    le = le.fit(df_train['C19'])
    df_train['C19'] = le.transform(df_train['C19'])

    le = le.fit(df_train['C20'])
    df_train['C20'] = le.transform(df_train['C20'])

    le = le.fit(df_train['C21'])
    df_train['C21'] = le.transform(df_train['C21'])
    
    df_train.head()

    return df_train

In [116]:
df_train = labelencording(df_train).copy()

In [117]:
df_train.head()

id  click      hour  C1  banner_pos  site_id  site_domain  \
0  1.000009e+18      0  14102100   2           0      442         4358   
1  1.000017e+19      0  14102100   2           0      442         4358   
2  1.000037e+19      0  14102100   2           0      442         4358   
3  1.000064e+19      0  14102100   2           0      442         4358   
4  1.000068e+19      0  14102100   2           1     3460         2624   

   site_category  app_id  app_domain ...   device_type  device_conn_type  C14  \
0              2    5031         175 ...             1                 1  256   
1              2    5031         175 ...             1                 0  254   
2              2    5031         175 ...             1                 0  254   
3              2    5031         175 ...             1                 0  256   
4              0    5031         175 ...             1                 0  389   

   C15  C16  C17  C18  C19  C20  C21  
0    3    2   50    0    2    0   20  
1    3    2   50    0    2   63   20  
2    3    2   50    0    2   63   20  
3    3    2   50    0    2   63   20  
4    3    2   96    0    2    0   37  

[5 rows x 24 columns]

## ターゲット変数と特徴量を指定してsklearnに渡せるように準備する

In [118]:
target_col = 'click'
exclude_cols = ['click', 'id', 'hour']
feature_cols = [col for col in df_train.columns if col not in exclude_cols]

In [119]:
feature_cols

['C1',
 'banner_pos',
 'site_id',
 'site_domain',
 'site_category',
 'app_id',
 'app_domain',
 'app_category',
 'device_id',
 'device_ip',
 'device_model',
 'device_type',
 'device_conn_type',
 'C14',
 'C15',
 'C16',
 'C17',
 'C18',
 'C19',
 'C20',
 'C21']

## 説明変数（特徴量）

In [120]:
df_train[feature_cols].head()

C1  banner_pos  site_id  site_domain  site_category  app_id  app_domain  \
0   2           0      442         4358              2    5031         175   
1   2           0      442         4358              2    5031         175   
2   2           0      442         4358              2    5031         175   
3   2           0      442         4358              2    5031         175   
4   2           1     3460         2624              0    5031         175   

   app_category  device_id  device_ip ...   device_type  device_conn_type  \
0             0     520971    1845413 ...             1                 1   
1             0     520971    1252534 ...             1                 0   
2             0     520971    1495906 ...             1                 0   
3             0     520971    1931641 ...             1                 0   
4             0     520971    1250578 ...             1                 0   

   C14  C15  C16  C17  C18  C19  C20  C21  
0  256    3    2   50    0    2    0   20  
1  254    3    2   50    0    2   63   20  
2  254    3    2   50    0    2   63   20  
3  256    3    2   50    0    2   63   20  
4  389    3    2   96    0    2    0   37  

[5 rows x 21 columns]

## 被説明変数（ターゲット変数）

In [121]:
df_train[target_col].head()

0    0
1    0
2    0
3    0
4    0
Name: click, dtype: int64

In [122]:
y = np.array(df_train[target_col])
X = np.array(df_train[feature_cols])

In [123]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [124]:
X

array([[   2,    0,  442, ...,    2,    0,   20],
       [   2,    0,  442, ...,    2,   63,   20],
       [   2,    0,  442, ...,    2,   63,   20],
       ...,
       [   2,    0, 1849, ...,    2,    0,    0],
       [   2,    0, 1849, ...,    2,   38,    0],
       [   2,    0, 1849, ...,    2,   86,    0]])

# モデルの作成

In [125]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [126]:
X_train, X_test, y_train, y_test = \
 train_test_split(X, y, test_size=0.3, random_state=1234)

In [127]:
X_train

array([[   2,    0, 1849, ...,   12,  161,   36],
       [   2,    0, 2978, ...,    2,   63,   41],
       [   2,    0,  442, ...,    2,    0,   41],
       ...,
       [   2,    0,  702, ...,    3,   56,    5],
       [   2,    0, 1298, ...,    2,   63,   41],
       [   2,    1,  218, ...,    3,   60,    6]])

## XGBoost

In [128]:
dtrain = xgb.DMatrix(X_train, label=y_train)
param = {'max_depth':3, 'learning_rate': 0.6, 'objective':'binary:logistic' }
num_round = 2
bst = xgb.train(param, dtrain, num_round)
preds = bst.predict(xgb.DMatrix(X_test))
print(accuracy_score(preds.round(), y_test))

[12:20:45] Tree method is automatically selected to be 'approx' for faster speed. to use old behavior(exact greedy algorithm on single machine), set tree_method to 'exact'
[12:21:01] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 14 extra nodes, 0 pruned nodes, max_depth=3
[12:21:12] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 14 extra nodes, 0 pruned nodes, max_depth=3
0.8340846666666667


In [129]:
preds

array([0.20377146, 0.24333918, 0.20377146, ..., 0.20377146, 0.18243341,
       0.20377146], dtype=float32)

## submission用csvの作成

In [210]:
test_fname = 'test.csv'
#reader_test = pd.read_csv(test_fname, chunksize=4577465,converters={'id':int})
#df_test_origin = reader_test.get_chunk(200000)
df_test_origin = pd.read_csv(test_fname,converters={'id':int})


In [208]:
df_test_origin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4577464 entries, 0 to 4577463
Data columns (total 23 columns):
id                  float64
hour                int64
C1                  int64
banner_pos          int64
site_id             object
site_domain         object
site_category       object
app_id              object
app_domain          object
app_category        object
device_id           object
device_ip           object
device_model        object
device_type         int64
device_conn_type    int64
C14                 int64
C15                 int64
C16                 int64
C17                 int64
C18                 int64
C19                 int64
C20                 int64
C21                 int64
dtypes: float64(1), int64(13), object(9)
memory usage: 803.2+ MB


In [209]:
df_test_origin['id'].head()

0    1.000017e+19
1    1.000018e+19
2    1.000055e+19
3    1.000109e+19
4    1.000138e+19
Name: id, dtype: float64

In [171]:
df_test_origin['id'] = df_test_origin['id'].apply(str)

In [172]:
df_test_origin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
id                  10000 non-null object
hour                10000 non-null int64
C1                  10000 non-null int64
banner_pos          10000 non-null int64
site_id             10000 non-null object
site_domain         10000 non-null object
site_category       10000 non-null object
app_id              10000 non-null object
app_domain          10000 non-null object
app_category        10000 non-null object
device_id           10000 non-null object
device_ip           10000 non-null object
device_model        10000 non-null object
device_type         10000 non-null int64
device_conn_type    10000 non-null int64
C14                 10000 non-null int64
C15                 10000 non-null int64
C16                 10000 non-null int64
C17                 10000 non-null int64
C18                 10000 non-null int64
C19                 10000 non-null int64
C20                 1

In [173]:
df_test_origin.head()

id      hour    C1  banner_pos   site_id site_domain  \
0  10000174058809263569  14103100  1005           0  235ba823    f6ebf28e   
1  10000182526920855428  14103100  1005           0  1fbe01fe    f3845767   
2  10000554139829213984  14103100  1005           0  1fbe01fe    f3845767   
3  10001094637809798845  14103100  1005           0  85f751fd    c4e18dd6   
4  10001377041558670745  14103100  1005           0  85f751fd    c4e18dd6   

  site_category    app_id app_domain app_category ...  device_type  \
0      f028772b  ecad2386   7801e8d9     07d7df22 ...            1   
1      28905ebd  ecad2386   7801e8d9     07d7df22 ...            1   
2      28905ebd  ecad2386   7801e8d9     07d7df22 ...            1   
3      50e219e0  51cedd4e   aefc06bd     0f2161f8 ...            1   
4      50e219e0  9c13b419   2347f47a     f95efa07 ...            1   

  device_conn_type    C14  C15  C16   C17  C18  C19     C20  C21  
0                0   8330  320   50   761    3  175  100075   23  
1                0  22676  320   50  2616    0   35  100083   51  
2                0  22676  320   50  2616    0   35  100083   51  
3                0  18648  320   50  1092    3  809  100156   61  
4                0  23160  320   50  2667    0   47      -1  221  

[5 rows x 23 columns]

In [174]:
df_test = labelencording(df_test_origin)

In [175]:
df_test.head()

id      hour  C1  banner_pos  site_id  site_domain  \
0  10000174058809263569  14103100   1           0       41          255   
1  10000182526920855428  14103100   1           0       34          253   
2  10000554139829213984  14103100   1           0       34          253   
3  10001094637809798845  14103100   1           0      156          208   
4  10001377041558670745  14103100   1           0      156          208   

   site_category  app_id  app_domain  app_category ...   device_type  \
0             11     266          16             0 ...             1   
1              1     266          16             0 ...             1   
2              1     266          16             0 ...             1   
3              4      90          21             2 ...             1   
4              4     181           5            14 ...             1   

   device_conn_type  C14  C15  C16  C17  C18  C19  C20  C21  
0                 0   19    2    1    8    3   11   32    4  
1                 0  248    2    1  102    0    1   37   10  
2                 0  248    2    1  102    0    1   37   10  
3                 0   91    2    1   15    3   26   64   12  
4                 0  323    2    1  120    0    5    0   27  

[5 rows x 23 columns]

In [176]:
df_test[feature_cols].head()

C1  banner_pos  site_id  site_domain  site_category  app_id  app_domain  \
0   1           0       41          255             11     266          16   
1   1           0       34          253              1     266          16   
2   1           0       34          253              1     266          16   
3   1           0      156          208              4      90          21   
4   1           0      156          208              4     181           5   

   app_category  device_id  device_ip ...   device_type  device_conn_type  \
0             0        836       3192 ...             1                 0   
1             0        836       6957 ...             1                 0   
2             0        836        532 ...             1                 0   
3             2        836       2015 ...             1                 0   
4            14        836        259 ...             1                 0   

   C14  C15  C16  C17  C18  C19  C20  C21  
0   19    2    1    8    3   11   32    4  
1  248    2    1  102    0    1   37   10  
2  248    2    1  102    0    1   37   10  
3   91    2    1   15    3   26   64   12  
4  323    2    1  120    0    5    0   27  

[5 rows x 21 columns]

In [177]:
df_test_origin['id'].apply(int)

0       10000174058809263569
1       10000182526920855428
2       10000554139829213984
3       10001094637809798845
4       10001377041558670745
5       10001521204153353724
6       10001911056707023378
7       10001982898844213216
8       10002000217531288531
9       10002107385290585663
10      10002121728305927027
11      10002246330438763746
12      10002274319697022546
13      10002614093820007721
14      10003085473872233973
15      10003460544097147762
16      10003655272218038955
17      10003886426122210904
18      10003962554013591855
19      10004028101361908315
20      10004147501365763118
21      10004218627354023598
22      10004594809490024984
23      10004595231242657912
24      10004844867110879461
25      10004882149038870218
26      10004964724620895563
27      10005270909407257114
28      10005321853961183294
29      10005377878485192027
                ...         
9970    11781593735255178037
9971    11781990618402229439
9972    11782089619358261594
9973     11782

In [178]:
answer = bst.predict(xgb.DMatrix(np.array(df_test[feature_cols])))


In [179]:
submit_data =  pd.Series(answer, name='click', index=df_test_origin['id'].apply(int))
submit_data.to_csv(submit_csv_name, header=True)

In [180]:
answer

array([0.23528723, 0.20377146, 0.20377146, ..., 0.28482   , 0.23528723,
       0.20377146], dtype=float32)